[package]
authors = ["Solana Maintainers <maintainers@solana.com>"]
edition = "2018"
name = "solana-net-shaper"
description = "The solana cluster network shaping tool"
version = "1.1.0"
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
publish = false

[dependencies]
clap = "2.33.0"
serde = "1.0.104"
serde_json = "1.0.48"
solana-clap-utils = { path = "../clap-utils", version = "1.1.0" }
solana-logger = { path = "../logger", version = "1.1.0" }
rand = "0.6.5"

[[bin]]
name = "solana-net-shaper"
path = "src/main.rs"
