[package]
name = "solana-bpf-loader-program"
version = "1.1.0"
description = "Solana BPF loader"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]
bincode = "1.2.1"
byteorder = "1.3.4"
libc = "0.2.66"
log = "0.4.8"
num-derive = { version = "0.3" }
num-traits = { version = "0.2" }
solana-logger = { path = "../../logger", version = "1.1.0" }
solana-sdk = { path = "../../sdk", version = "1.1.0" }
solana_rbpf = "=0.1.21"
thiserror = "1.0"

[lib]
crate-type = ["lib", "cdylib"]
name = "solana_bpf_loader_program"
