[package]
name = "solana-ledger"
version = "1.1.0"
description = "Solana ledger"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
homepage = "https://solana.com/"
edition = "2018"

[dependencies]
bincode = "1.2.1"
byteorder = "1.3.4"
bzip2 = "0.3.3"
chrono = { version = "0.4.10", features = ["serde"] }
crossbeam-channel = "0.4"
dir-diff = "0.3.2"
sha2 = "0.8.1"
fs_extra = "1.1.0"
itertools = "0.8.2"
libc = "0.2.66"
log = { version = "0.4.8" }
rand = "0.6.5"
rand_chacha = "0.1.1"
rayon = "1.2.0"
reed-solomon-erasure = { package = "solana-reed-solomon-erasure", version = "4.0.1-3", features = ["simd-accel"] }
serde = "1.0.104"
serde_bytes = "0.11.3"
solana-client = { path = "../client", version = "1.1.0" }
solana-genesis-programs = { path = "../genesis-programs", version = "1.1.0" }
solana-logger = { path = "../logger", version = "1.1.0" }
solana-measure = { path = "../measure", version = "1.1.0" }
solana-merkle-tree = { path = "../merkle-tree", version = "1.1.0" }
solana-metrics = { path = "../metrics", version = "1.1.0" }
solana-perf = { path = "../perf", version = "1.1.0" }
ed25519-dalek = "1.0.0-pre.1"
solana-rayon-threadlimit = { path = "../rayon-threadlimit", version = "1.1.0" }
solana-runtime = { path = "../runtime", version = "1.1.0" }
solana-sdk = { path = "../sdk", version = "1.1.0" }
solana-stake-program = { path = "../programs/stake", version = "1.1.0" }
solana-vote-program = { path = "../programs/vote", version = "1.1.0" }
sys-info = "0.5.9"
symlink = "0.1.0"
tar = "0.4.26"
thiserror = "1.0"
tempfile = "3.1.0"
lazy_static = "1.4.0"

[dependencies.rocksdb]
# Avoid the vendored bzip2 within rocksdb-sys that can cause linker conflicts
# when also using the bzip2 crate
version = "0.13.0"
default-features = false
features = ["lz4"]

[dev-dependencies]
assert_matches = "1.3.0"
matches = "0.1.6"
solana-budget-program = { path = "../programs/budget", version = "1.1.0" }

[lib]
crate-type = ["lib"]
name = "solana_ledger"

[[bench]]
name = "sigverify_shreds"
