[package]
name = "solana-upload-perf"
version = "1.1.0"
description = "Metrics Upload Utility"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
license = "Apache-2.0"
edition = "2018"
homepage = "https://solana.com/"
publish = false

[dependencies]
serde_json = "1.0.48"
solana-metrics = { path = "../metrics", version = "1.1.0" }

[[bin]]
name = "solana-upload-perf"
path = "src/upload-perf.rs"

