[package]
name = "solana-sdk"
version = "1.1.0"
description = "Solana SDK"
authors = ["Solana Maintainers <maintainers@solana.com>"]
repository = "https://github.com/solana-labs/solana"
homepage = "https://solana.com/"
license = "Apache-2.0"
edition = "2018"

[features]
# On-chain program specific dependencies
program = []
# Dependencies that are not compatible or needed for on-chain programs
default = [
    "assert_matches",
    "byteorder",
    "memmap",
    "rand",
    "rand_chacha",
    "serde_json",
    "ed25519-dalek",
    "solana-logger",
    "solana-crate-features"
]

[dependencies]
assert_matches = { version = "1.3.0", optional = true }
bincode = "1.2.1"
bs58 = "0.3.0"
bv = { version = "0.11.0", features = ["serde"] }
byteorder = { version = "1.3.2", optional = true }
generic-array = { version = "0.13.2", default-features = false, features = ["serde", "more_lengths"] }
hex = "0.4.0"
hmac = "0.7.0"
itertools = { version = "0.8.2" }
log = { version = "0.4.8" }
memmap = { version = "0.7.0", optional = true }
num-derive = { version = "0.3" }
num-traits = { version = "0.2" }
pbkdf2 = { version = "0.3.0", default-features = false }
rand = { version = "0.6.5", optional = true }
rand_chacha = { version = "0.1.1", optional = true }
serde = "1.0.104"
serde_bytes = "0.11"
serde_derive = "1.0.103"
serde_json = { version = "1.0.48", optional = true }
sha2 = "0.8.1"
thiserror = "1.0"
ed25519-dalek = { version = "=1.0.0-pre.1", optional = true }
solana-crate-features = { path = "../crate-features", version = "1.1.0", optional = true }
solana-logger = { path = "../logger", version = "1.1.0", optional = true }
solana-sdk-macro = { path = "macro", version = "1.1.0" }

[dev-dependencies]
tiny-bip39 = "0.7.0"
